/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.registrationcenter;

import Business.RegCenter.Donor;
import Business.RegCenter.Organ;
import java.awt.CardLayout;
import java.awt.Font;
import javax.swing.JPanel;

/**
 *
 * @author Neha
 */
public class ViewDonorDetailsPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Donor donor;
    /**
     * Creates new form SurgeryDetails
     */
    public ViewDonorDetailsPanel(JPanel userProcessContainer, Donor donor) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.donor=donor;
        donorDetailsTabbedPanel.setFont( new Font("Segoe UI Semibold", Font.PLAIN, 18 ) );
        populateForm();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        donorDetailsTabbedPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        donorNameTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        donorIDTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        genderTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        telephoneTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        DonorAgeLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        bloodGroupTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        weightTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        heightTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        bmiTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        kidney = new javax.swing.JCheckBox();
        liver = new javax.swing.JCheckBox();
        lungs = new javax.swing.JCheckBox();
        pancreas = new javax.swing.JCheckBox();
        intestine = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Donor Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 39, 281, -1));

        backBtn.setBackground(new java.awt.Color(0, 0, 0));
        backBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 153, 153));
        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 706, -1, -1));

        donorDetailsTabbedPanel.setBackground(new java.awt.Color(204, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel9.setText("Donor Name :");

        donorNameTextField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        donorNameTextField.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel8.setText("Donor ID :");

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel17.setText("Email:");

        donorIDTextField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        donorIDTextField.setEnabled(false);

        emailTextField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        emailTextField.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel16.setText("Address:");

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel15.setText("Gender:");

        genderTextField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        genderTextField.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel12.setText("Telephone:");

        telephoneTextField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        telephoneTextField.setEnabled(false);

        ageTextField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        ageTextField.setEnabled(false);

        DonorAgeLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        DonorAgeLabel.setText("Age : ");

        addressTextField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        addressTextField.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(telephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(DonorAgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel8))
                                    .addGap(128, 128, 128))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(97, 97, 97)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(donorNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(donorIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(donorIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(donorNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DonorAgeLabel)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(telephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        donorDetailsTabbedPanel.addTab("Personal Details", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        bloodGroupTextField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        bloodGroupTextField.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel11.setText("Blood Group:");

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel14.setText("Body weight:");

        weightTextField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        weightTextField.setEnabled(false);

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel18.setText("Height:");

        heightTextField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        heightTextField.setEnabled(false);

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel19.setText("BMI:");

        bmiTextField.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        bmiTextField.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setText("Organs Donating :");

        kidney.setBackground(new java.awt.Color(0, 204, 204));
        kidney.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        kidney.setText("Kidney");
        kidney.setEnabled(false);

        liver.setBackground(new java.awt.Color(0, 204, 204));
        liver.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        liver.setText("Liver");
        liver.setEnabled(false);
        liver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liverActionPerformed(evt);
            }
        });

        lungs.setBackground(new java.awt.Color(0, 204, 204));
        lungs.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lungs.setText("Lungs");
        lungs.setEnabled(false);

        pancreas.setBackground(new java.awt.Color(0, 204, 204));
        pancreas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        pancreas.setText("Pancreas");
        pancreas.setEnabled(false);

        intestine.setBackground(new java.awt.Color(0, 204, 204));
        intestine.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        intestine.setText("Intestine");
        intestine.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bloodGroupTextField)
                            .addComponent(weightTextField)
                            .addComponent(heightTextField)
                            .addComponent(bmiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kidney)
                            .addComponent(pancreas))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(liver)
                                .addGap(33, 33, 33)
                                .addComponent(lungs))
                            .addComponent(intestine))))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(bloodGroupTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(bmiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kidney)
                    .addComponent(liver)
                    .addComponent(lungs))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pancreas)
                    .addComponent(intestine))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        donorDetailsTabbedPanel.addTab("Medical Details", jPanel2);

        add(donorDetailsTabbedPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void liverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_liverActionPerformed

    private void populateForm(){
       donorIDTextField.setText(donor.getDonorId());
       donorNameTextField.setText(donor.getDonorName());
       genderTextField.setText(donor.getDonorGender());
       addressTextField.setText(donor.getDonorAddress());
       ageTextField.setText(String.valueOf(donor.getDonorAge()));
       bloodGroupTextField.setText(donor.getHealthDetails().getBloodGroup());
       telephoneTextField.setText(String.valueOf(donor.getDonorPhoneNumber()));
       emailTextField.setText(donor.getDonorEmailId());
       weightTextField.setText(String.valueOf(donor.getHealthDetails().getWeight()));
       heightTextField.setText(String.valueOf(donor.getHealthDetails().getHeight()));
       bmiTextField.setText(String.valueOf(calculateBmi(donor.getHealthDetails().getHeight(), donor.getHealthDetails().getWeight())));
       
       for(Organ organ : donor.getOrganDonateList()){
          if(organ.getOrganName().equalsIgnoreCase("Kidney")){
              kidney.setSelected(true);
          }
          if(organ.getOrganName().equalsIgnoreCase("Liver")){
              liver.setSelected(true);
          }
          if(organ.getOrganName().equalsIgnoreCase("Lungs")){
              lungs.setSelected(true);
          }
          if(organ.getOrganName().equalsIgnoreCase("Pancreas")){
              pancreas.setSelected(true);
          }
          if(organ.getOrganName().equalsIgnoreCase("intestines")){
              intestine.setSelected(true);
          }
       }
       
    }
    
    public float calculateBmi(int height, float weight){
        
        float bmi = (weight/(height*height))*10000;
        return bmi;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DonorAgeLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField bloodGroupTextField;
    private javax.swing.JTextField bmiTextField;
    private javax.swing.JTabbedPane donorDetailsTabbedPanel;
    private javax.swing.JTextField donorIDTextField;
    private javax.swing.JTextField donorNameTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField genderTextField;
    private javax.swing.JTextField heightTextField;
    private javax.swing.JCheckBox intestine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox kidney;
    private javax.swing.JCheckBox liver;
    private javax.swing.JCheckBox lungs;
    private javax.swing.JCheckBox pancreas;
    private javax.swing.JTextField telephoneTextField;
    private javax.swing.JTextField weightTextField;
    // End of variables declaration//GEN-END:variables
}
