/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OPTEAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FindDonorRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Neha
 */
public class OPTEAdminWorkArea extends javax.swing.JPanel {
private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Network network;
    private UserAccount account;
    /**
     * Creates new form OPTDAdminWorkArea
     */
    public OPTEAdminWorkArea(JPanel userProcessContainer,UserAccount account, Enterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.network=network;
        this.account=account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        manageEmployeeBtn = new javax.swing.JButton();
        manageUsersBtn = new javax.swing.JButton();
        manageOPTBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 20)); // NOI18N
        jLabel1.setText("OPTD ADMIN WORK AREA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 370, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        manageEmployeeBtn.setBackground(new java.awt.Color(0, 0, 0));
        manageEmployeeBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        manageEmployeeBtn.setForeground(new java.awt.Color(255, 153, 153));
        manageEmployeeBtn.setText("Manage Employees");
        manageEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeBtnActionPerformed(evt);
            }
        });

        manageUsersBtn.setBackground(new java.awt.Color(0, 0, 0));
        manageUsersBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        manageUsersBtn.setForeground(new java.awt.Color(255, 153, 153));
        manageUsersBtn.setText("Manage Users");
        manageUsersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUsersBtnActionPerformed(evt);
            }
        });

        manageOPTBtn.setBackground(new java.awt.Color(0, 0, 0));
        manageOPTBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        manageOPTBtn.setForeground(new java.awt.Color(255, 153, 153));
        manageOPTBtn.setText("Manage Organ Procurement and Transplantation");
        manageOPTBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOPTBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageUsersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageEmployeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(manageOPTBtn)
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(manageEmployeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(manageUsersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(manageOPTBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 610, 330));
    }// </editor-fold>//GEN-END:initComponents

    private void manageEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeBtnActionPerformed
        ManageOPTEEmployeesPanel manageOPTEEmployeesPanel = new ManageOPTEEmployeesPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("ManageOPTEEmployeesPanel",manageOPTEEmployeesPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEmployeeBtnActionPerformed

    private void manageUsersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUsersBtnActionPerformed
        ManageOTPEUsersPanel muajp = new ManageOTPEUsersPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageOTPEUsersPanel", muajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageUsersBtnActionPerformed

    private void manageOPTBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOPTBtnActionPerformed
        
        OrganProcurementAndTransplantationPanel opt = new OrganProcurementAndTransplantationPanel(userProcessContainer,account, enterprise,network);
        userProcessContainer.add("OrganProcurementAndTransplantation", opt);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOPTBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manageEmployeeBtn;
    private javax.swing.JButton manageOPTBtn;
    private javax.swing.JButton manageUsersBtn;
    // End of variables declaration//GEN-END:variables
}
