/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OPTEAdminRole;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.OPTOrganization.OPTEAdminOrganization;
import Business.Organization.OPTOrganization.SurgeonOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FindDonorRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neha
 */
public class OrganProcurementAndTransplantationPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrganProcurementAndTransplantation
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private  Network network;
    private UserAccount account;

    public OrganProcurementAndTransplantationPanel(JPanel userProcessContainer,UserAccount account, Enterprise enterprise, Network network){
         initComponents();
          this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.network=network;
        this.account=account;
         populateOPTEWorkRequest();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        opteWorkRequestTable = new javax.swing.JTable();
        scheduleProcAndTransBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        opteWorkRequestTable.setBackground(new java.awt.Color(204, 255, 255));
        opteWorkRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RequestID", "Hospital ID", "PatientID", "Patient Name", "Donor ID", "Donor Name", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(opteWorkRequestTable);
        if (opteWorkRequestTable.getColumnModel().getColumnCount() > 0) {
            opteWorkRequestTable.getColumnModel().getColumn(0).setPreferredWidth(30);
            opteWorkRequestTable.getColumnModel().getColumn(2).setPreferredWidth(30);
            opteWorkRequestTable.getColumnModel().getColumn(4).setPreferredWidth(30);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 910, 490));

        scheduleProcAndTransBtn.setBackground(new java.awt.Color(0, 0, 0));
        scheduleProcAndTransBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        scheduleProcAndTransBtn.setForeground(new java.awt.Color(255, 153, 153));
        scheduleProcAndTransBtn.setText("Schedule Procurement and Transplant");
        scheduleProcAndTransBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleProcAndTransBtnActionPerformed(evt);
            }
        });
        add(scheduleProcAndTransBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 610, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 20)); // NOI18N
        jLabel1.setText("Organ Procurement and Transplantation Work Queue");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 580, -1));

        backBtn.setBackground(new java.awt.Color(0, 0, 0));
        backBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 153, 153));
        backBtn.setText("<<Back ");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 660, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void scheduleProcAndTransBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleProcAndTransBtnActionPerformed
            int selectedRow= opteWorkRequestTable.getSelectedRow();
       if (selectedRow>=0)
       {
        FindDonorRequest request= (FindDonorRequest)opteWorkRequestTable.getValueAt(selectedRow, 0);
        request.setSender(account);
        request.setStatus("Procurement Pending");
        
           Organization org = null;
          
           for (Network city : network.getSubNetwork()) {
               for (Enterprise enterprise : city.getEnterpriseDirectory().getEnterpriseList()) {
                   if (enterprise.getEnterpriseType().getValue().equals(Enterprise.EnterpriseType.OrganProcAndTransCenter.toString())) {
                       for (UserAccount ua : enterprise.getUserAccountDirectory().getUserAccountList()) {
                           if (ua.equals(account)) {
                               for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                                   if (organization instanceof SurgeonOrganization) {
                                       org = organization;
                                       break;
                                   }
                               }
                           }
                       }

                   }
               }
           }

           
        
        
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
        }
        
         JOptionPane.showMessageDialog(this, "Procurement and Transplantation initiated!");
       }
       else{
           
           JOptionPane.showMessageDialog(this, "Please select a row", "Error", JOptionPane.ERROR_MESSAGE);
       } 
    }//GEN-LAST:event_scheduleProcAndTransBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed
    public void populateOPTEWorkRequest(){
        opteWorkRequestTable.getTableHeader().setFont(new Font("Segoe UI Semibold", Font.PLAIN, 18));
        DefaultTableModel model = (DefaultTableModel) opteWorkRequestTable.getModel();
        model.setRowCount(0);
        for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
        if(organization instanceof OPTEAdminOrganization)    {
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[7];
            row[0] = request;
            row[1] = ((FindDonorRequest) request).getHospitalID();
            row[2] = ((FindDonorRequest) request).getPatientDetails().getPatientID();
            row[3] = ((FindDonorRequest) request).getPatientDetails().getPatientName();
            row[4] = ((FindDonorRequest) request).getDonor().getDonorId();
            row[5] = ((FindDonorRequest) request).getDonor().getDonorName();
            row[6] = ((FindDonorRequest) request).getStatus();
            model.addRow(row);
        }
        }
     }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable opteWorkRequestTable;
    private javax.swing.JButton scheduleProcAndTransBtn;
    // End of variables declaration//GEN-END:variables
}
