/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CountryNetworkAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import userinterface.StateNetworkAdminRole.StateReportsJPanel;

/**
 *
 * @author Neha
 */
public class CountryNetworkAdminWorkArea extends javax.swing.JPanel {
      private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount account;
    private Network countryNetwork;
    /**
     * Creates new form NetworkAdminWorkArea
     */
      
    public CountryNetworkAdminWorkArea(JPanel userProcessContainer, UserAccount account , EcoSystem system,Network countryNetwork) {
        initComponents();
            this.userProcessContainer = userProcessContainer;
         this.system = system;
         this.account = account;
         this.countryNetwork=countryNetwork;
         employeeNameLabel.setHorizontalAlignment(HEIGHT);
         employeeNameLabel.setText(account.getEmployee().getName());
         populateTree();
    }
    
    public void populateTree(){
        DefaultTreeModel treeModel = (DefaultTreeModel) NetworkJTree.getModel();
        ArrayList<Network> networkList = system.getNetworkList();
        ArrayList<Enterprise> enterpriseList;
        ArrayList<Organization> organizationList;
        
        Network network;
        Enterprise enterprise;
        Organization organization;
        Network stateNetwork;
        Network cityNetwork;
        
        DefaultMutableTreeNode rootNetwork = new DefaultMutableTreeNode("Network");
        DefaultMutableTreeNode root = (DefaultMutableTreeNode)treeModel.getRoot();
        root.removeAllChildren();
        root.insert(rootNetwork,0);
        
        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode stateNetworkNode;
        DefaultMutableTreeNode cityNetworkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;
        
        for(int i = 0; i<networkList.size(); i++){
            network = networkList.get(i);
            if(network.getUserAccountDirectory().getUserAccountList().size() > 0){
                if(network.getUserAccountDirectory().getUserAccountList().get(0).getUsername().equals(account.getUsername())){
                 networkNode = new DefaultMutableTreeNode(network.getNetworkName());
                 rootNetwork.insert(networkNode, 0);
            
            for(int j = 0 ; j<network.getSubNetwork().size(); j++){
                stateNetwork = network.getSubNetwork().get(j);
                stateNetworkNode = new DefaultMutableTreeNode(stateNetwork.getNetworkName());
                networkNode.insert(stateNetworkNode, j);
                
                
                for(int k = 0; k<stateNetwork.getSubNetwork().size(); k++){
                   cityNetwork = stateNetwork.getSubNetwork().get(k);
                   cityNetworkNode = new DefaultMutableTreeNode(cityNetwork.getNetworkName());
                   stateNetworkNode.insert(cityNetworkNode, k);
                   
                   enterpriseList = cityNetwork.getEnterpriseDirectory().getEnterpriseList();
                   for(int a = 0; a<enterpriseList.size(); a++){
                      enterprise = enterpriseList.get(a);
                      enterpriseNode = new DefaultMutableTreeNode(enterprise.getName());
                      cityNetworkNode.insert(enterpriseNode, a);
                
                      organizationList = enterprise.getOrganizationDirectory().getOrganizationList();
                
                      for(int b = 0; b< organizationList.size(); b++){
                          organization = organizationList.get(b);
                          organizationNode = new DefaultMutableTreeNode(organization.getName());
                          enterpriseNode.insert(organizationNode, b);
                      }
                    } 
                }
            } 
            }
            }
            
                   
        }
        treeModel.reload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        NetworkJTree = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        manageStateNetworkAdminBtn = new javax.swing.JButton();
        manageRequestsBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        userAccImgLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        employeeNameLabel = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTree1);

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NetworkJTree.setBackground(new java.awt.Color(204, 255, 255));
        NetworkJTree.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("System");
        NetworkJTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(NetworkJTree);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 174, 652));

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        manageStateNetworkAdminBtn.setBackground(new java.awt.Color(0, 0, 0));
        manageStateNetworkAdminBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        manageStateNetworkAdminBtn.setForeground(new java.awt.Color(255, 153, 153));
        manageStateNetworkAdminBtn.setText("Manage State Network Admin");
        manageStateNetworkAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStateNetworkAdminBtnActionPerformed(evt);
            }
        });

        manageRequestsBtn.setBackground(new java.awt.Color(0, 0, 0));
        manageRequestsBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        manageRequestsBtn.setForeground(new java.awt.Color(255, 153, 153));
        manageRequestsBtn.setText("Manage WorkRequests");
        manageRequestsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRequestsBtnActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 153));
        jButton1.setText("View Reports");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageRequestsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageStateNetworkAdminBtn))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(manageStateNetworkAdminBtn)
                .addGap(45, 45, 45)
                .addComponent(manageRequestsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 380, 300));

        userAccImgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/SystemAdminWorkArea/sysadmin.png"))); // NOI18N
        add(userAccImgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("Welcome ! ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, -1, -1));

        employeeNameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        add(employeeNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 150, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void manageRequestsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRequestsBtnActionPerformed
      CountryNetworkAdminWorkRequestArea countryNetworkAdminWorkRequestArea = new CountryNetworkAdminWorkRequestArea(userProcessContainer,account, system,countryNetwork);
        userProcessContainer.add("countryNetworkAdminWorkRequestArea",countryNetworkAdminWorkRequestArea);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageRequestsBtnActionPerformed

    private void manageStateNetworkAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStateNetworkAdminBtnActionPerformed
        ManageStateNetworkAdminJPanl manageNetworkAdmin = new ManageStateNetworkAdminJPanl(userProcessContainer,account, system);
        userProcessContainer.add("ManageNetworkAdminJPanel",manageNetworkAdmin);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageStateNetworkAdminBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       CountryReportsJPanel registeredDonorsReport = new CountryReportsJPanel(userProcessContainer,countryNetwork);
        userProcessContainer.add("StateReportsJPanel",registeredDonorsReport);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree NetworkJTree;
    private javax.swing.JLabel employeeNameLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton manageRequestsBtn;
    private javax.swing.JButton manageStateNetworkAdminBtn;
    private javax.swing.JLabel userAccImgLabel;
    // End of variables declaration//GEN-END:variables
}
