/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.registrationcenter.AdministrativeRole;

import Business.EcoSystem;
import Business.Enterprise.DonorRegistrationCenter;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.InitialScreeningTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ApoorvaLakhmani
 */
public class DonorRequestStatusJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount account;
    private EcoSystem system;
    private Network stateNetwork;
    /**
     * Creates new form DonorRequestStatusJPanel
     */
    public DonorRequestStatusJPanel(JPanel userProcessContainers,Enterprise enterprise,UserAccount account,EcoSystem system,Network stateNetwork) {
        initComponents();
        this.userProcessContainer = userProcessContainers;
        this.enterprise = enterprise;
        this.account = account;
        this.system = system;
        this.stateNetwork = stateNetwork;
        
        populateTable();
    }
    
    public void populateTable(){
        DononrRegReqTable.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 20));
        DefaultTableModel model = (DefaultTableModel) DononrRegReqTable.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : account.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[2];
            row[0] = request;
            row[1] = request.getStatus();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DononrRegReqTable = new javax.swing.JTable();
        RegisterDonorBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DononrRegReqTable.setBackground(new java.awt.Color(204, 255, 255));
        DononrRegReqTable.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        DononrRegReqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Donor Name", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(DononrRegReqTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 54, -1, 164));

        RegisterDonorBtn.setBackground(new java.awt.Color(0, 0, 0));
        RegisterDonorBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        RegisterDonorBtn.setForeground(new java.awt.Color(255, 153, 153));
        RegisterDonorBtn.setText("Register Donor");
        RegisterDonorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterDonorBtnActionPerformed(evt);
            }
        });
        add(RegisterDonorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 287, 50));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 153));
        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 394, 100, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterDonorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterDonorBtnActionPerformed
        
       int selectedRow= DononrRegReqTable.getSelectedRow();
       if (selectedRow>=0)
       {
         InitialScreeningTestWorkRequest request= (InitialScreeningTestWorkRequest)DononrRegReqTable.getValueAt(selectedRow, 0);
         if(request.getStatus().equals("Initial Screening Done")&& (request.getTestResult() == null || !request.getTestResult().equalsIgnoreCase("Cant be an organ donor"))
                                                                             ){
             request.setStatus("Registeration complete");
             request.getDonor().setIsAvailable(true);
             system.getMasterDonorDirectory().add(request.getDonor());
             stateNetwork.getDonorDirectory().addDonor(request.getDonor());
             ((DonorRegistrationCenter)enterprise).getDonorDirectory().addDonor(request.getDonor());
             populateTable();
             JOptionPane.showMessageDialog(this, "Donor Registered!");
             
         }
         else if(request.getStatus().equals("Initial Screening pending")){
             JOptionPane.showMessageDialog(this, "Request is not in proper status to register the Donor!");
           
         }
         else if(request.getStatus().equals("Initial Screening Done")&& request.getTestResult().equalsIgnoreCase("Cant be an organ donor")){
             
             request.setStatus("Cannot be a donor");
               JOptionPane.showMessageDialog(this, "Request updated!");
             populateTable();
         }
       }
       else{
           
           JOptionPane.showMessageDialog(this, "Please select a row", "Error", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_RegisterDonorBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DononrRegReqTable;
    private javax.swing.JButton RegisterDonorBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
