/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HospitalAdminRole;

import Business.EcoSystem;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FindDonorRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Font;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neha
 */
public class RaiseAndViewMyRequests extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem system;
    private Network network;
    private UserAccount userAccount;
    
    /**
     * Creates new form RaiseAndViewMyRequests
     */
    public RaiseAndViewMyRequests(JPanel userProcessContainer,UserAccount userAccount,Network network,EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.network = network;
        this.system=system; 
        this.userAccount = userAccount;
        populateTable();
    }
    
    public void populateTable(){
        RequestDetailsTable.getTableHeader().setFont(new Font("Segoe UI Semibold", Font.PLAIN, 18));
        DefaultTableModel model = (DefaultTableModel) RequestDetailsTable.getModel();
        model.setRowCount(0);
         Date dateWithZeroTime=null;
         Date completionDate=null;
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[7];
            row[0] = request.getRequestID();
            DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
            Date reqDate = request.getRequestDate(); 
             Date processCompletonDate=((FindDonorRequest)request).getResolveDate();
            try {
               dateWithZeroTime = formatter.parse(formatter.format(reqDate));
               if (processCompletonDate!=null){
                   completionDate=formatter.parse(formatter.format(processCompletonDate));
               }
               
            } catch (ParseException ex) {
                Logger.getLogger(RaiseAndViewMyRequests.class.getName()).log(Level.SEVERE, null, ex);
            }
            row[1] = dateWithZeroTime;
             row[2] = ((FindDonorRequest)request).getPatientDetails().getPatientID();
             row[3] = ((FindDonorRequest)request).getPatientDetails().getPatientName();
             row[4] = ((FindDonorRequest)request).getPatientDetails().getOrganNeeded().getOrganName();
            row[5] = request.getStatus();
            row[6] = processCompletonDate == null ? "" : completionDate;
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RaiseReqBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        RequestDetailsTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RaiseReqBtn.setBackground(new java.awt.Color(0, 0, 0));
        RaiseReqBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        RaiseReqBtn.setForeground(new java.awt.Color(255, 153, 153));
        RaiseReqBtn.setText("Raise new request>>");
        RaiseReqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RaiseReqBtnActionPerformed(evt);
            }
        });
        add(RaiseReqBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 480, -1, -1));

        RequestDetailsTable.setBackground(new java.awt.Color(204, 255, 255));
        RequestDetailsTable.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        RequestDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Request Date", "Patient ID", "Patient Name", "Organ", "Status", "Process Completion date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(RequestDetailsTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 171, 980, 192));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 20)); // NOI18N
        jLabel1.setText("My Work Requests");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 86, 201, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 153));
        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void RaiseReqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RaiseReqBtnActionPerformed
       RaiseNewRequestPanel raiseNewRequest = new RaiseNewRequestPanel(userProcessContainer,userAccount,network,system);
       userProcessContainer.add("RaiseAndViewMyRequests",raiseNewRequest);
       CardLayout layout = (CardLayout)userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_RaiseReqBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RaiseReqBtn;
    private javax.swing.JTable RequestDetailsTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
