/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StateNetworkAdminRole;

import Business.RegCenter.Donor;
import Business.RegCenter.DonorDirectory;
import java.awt.CardLayout;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.registrationcenter.ViewDonorDetailsPanel;

/**
 *
 * @author ApoorvaLakhmani
 */
public class RegisteredDonorsListJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private DonorDirectory donorDirectory;

    /**
     * Creates new form RegisteredDonorsListJPanel
     */
    public RegisteredDonorsListJPanel(JPanel userProcessContainer, DonorDirectory donorDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.donorDirectory = donorDirectory;
        
        populateTable();
    }
    
    public void populateTable(){
        donorDetailsTable.getTableHeader().setFont(new Font("Segoe UI Semibold", Font.PLAIN, 20));
        DefaultTableModel model = (DefaultTableModel) donorDetailsTable.getModel();
        model.setRowCount(0);
        
        for(Donor donor : donorDirectory.getDonorList()){
            Object[] row = new Object[2];
            row[0] = donor;
            row[1] = donor.getDonorName();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        donorDetailsTable = new javax.swing.JTable();
        viewDonorDetailsBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        donorDetailsTable.setBackground(new java.awt.Color(204, 255, 255));
        donorDetailsTable.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        donorDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Donor ID", "Donor Name"
            }
        ));
        jScrollPane1.setViewportView(donorDetailsTable);

        viewDonorDetailsBtn.setBackground(new java.awt.Color(0, 0, 0));
        viewDonorDetailsBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        viewDonorDetailsBtn.setForeground(new java.awt.Color(255, 153, 153));
        viewDonorDetailsBtn.setText("View Details");
        viewDonorDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDonorDetailsBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(0, 0, 0));
        backBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 153, 153));
        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(viewDonorDetailsBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(backBtn)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(viewDonorDetailsBtn)
                .addGap(43, 43, 43)
                .addComponent(backBtn)
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewDonorDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDonorDetailsBtnActionPerformed
       int selectedRow= donorDetailsTable.getSelectedRow();
       if (selectedRow>=0)
       {
       Donor donor= (Donor)donorDetailsTable.getValueAt(selectedRow, 0);
       ViewDonorDetailsPanel viewDonorDetails = new ViewDonorDetailsPanel(userProcessContainer,donor);
       userProcessContainer.add("ViewDonorDetailsPanel", viewDonorDetails);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.next(userProcessContainer);
       }
       else{
           
           JOptionPane.showMessageDialog(this, "Please select a row", "Error", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_viewDonorDetailsBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable donorDetailsTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewDonorDetailsBtn;
    // End of variables declaration//GEN-END:variables
}
